### ISSUE TITLE
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'

### ISSUE THREAD

**Issue by dtheb** [nikdoof/python-ts3#10]
hello,

am trying to test this API but am stuck with this error full output:

D:\DEV\py341\python.exe D:/DEV/workspace/py/hellow/main.py
Traceback (most recent call last):
  File "D:/DEV/workspace/py/hellow/main.py", line 4, in <module>
    server.login('user', 'pass')
  File "D:\DEV\py341\lib\site-packages\python_ts3-0.1-py3.4.egg\ts3\server.py", line 64, in login
  File "D:\DEV\py341\lib\site-packages\python_ts3-0.1-py3.4.egg\ts3\protocol.py", line 129, in send_command
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'

Process finished with exit code 1

**Comment by nikdoof** [comment]
Should be resolved by commit 74b350e9dd3e6f98dab118358eba68694695db91
